"""
Optimized OpenVoice voice cloner -- VRAM-aware, CPU-fallback, concurrent cloning.

Satisfies the VoiceCloner Protocol defined in pipeline/vc_base.py.
"""

from __future__ import annotations

import gc
import hashlib
import os
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Optional

import torch

from .vc_base import VoiceCloneConfig
from .vc_device import detect_vram_mb


class OpenVoiceCloner:
    """VRAM-aware OpenVoice v2 voice cloner.

    Low-VRAM mode (<4 GB):  CPU-only, int8 Whisper, watermark disabled.
    High-VRAM mode (>=4 GB): GPU with concurrent clone via ThreadPoolExecutor.

    Speaker embeddings are persisted to disk (models/.se_cache/) so that the
    same reference audio only incurs Whisper inference once across sessions.
    """

    # ------------------------------------------------------------------
    # Initialisation
    # ------------------------------------------------------------------

    def __init__(self, config: VoiceCloneConfig) -> None:
        self.config = config

        # --- VRAM-aware mode selection ---------------------------------
        vram_mb = detect_vram_mb()

        if vram_mb >= 8192:
            self._mode = "gpu"
            self._concurrency = min(config.concurrent_workers, 4)
        elif vram_mb >= 4096:
            self._mode = "gpu"
            self._concurrency = min(config.concurrent_workers, 2)
        else:
            self._mode = "cpu"
            self._concurrency = 1

        if self._mode == "cpu":
            self._device = "cpu"
            self._compute_type = "int8"
            self._enable_watermark = False
        else:
            self._device = self._resolve_device(config.device)
            self._compute_type = "float16"
            self._enable_watermark = config.enable_watermark

        self._vram_mb = vram_mb

        # --- Internal state --------------------------------------------
        self._model: Optional[object] = None
        self._embedding: Optional[torch.Tensor] = None   # tgt_se: target voice
        self._src_embedding: Optional[torch.Tensor] = None  # src_se: TTS voice
        self._lock = threading.Lock()
        self._embedding_cache_dir = config.se_cache_dir
        os.makedirs(self._embedding_cache_dir, exist_ok=True)

    # ------------------------------------------------------------------
    # VoiceCloner Protocol
    # ------------------------------------------------------------------

    def prepare(self, voice_path: str) -> bool:
        """Extract and cache the speaker embedding from the color audio.

        Args:
            voice_path: Path to the reference vocal WAV (Demucs output).
                Falls back to ``config.color_audio_path`` if that exists.

        Returns:
            ``True`` on success, ``False`` on failure.
        """
        color_path = self.config.color_audio_path

        if not os.path.isfile(color_path):
            if voice_path and os.path.isfile(voice_path):
                color_path = voice_path
            else:
                self._log_error(
                    f"参考音频不存在: color={color_path}, voice={voice_path}"
                )
                return False

        try:
            self._embedding = self._extract_or_load_embedding(color_path)
            self._src_embedding = None  # reset when reference changes
            return True
        except Exception as exc:
            self._log_error(f"prepare 失败 [{color_path}]: {exc}")
            return False

    def clone(self, tts_audio_path: str, output_dir: str) -> Optional[str]:
        """Convert the TTS audio to the target speaker timbre.

        Extracts source embedding from the TTS audio and target embedding
        from the color reference, then runs tone color conversion.

        Thread-safe: multiple callers may invoke ``clone()`` concurrently; the
        shared model is guarded by a lock.

        Args:
            tts_audio_path: Path to the audio generated by the TTS engine.
            output_dir: Directory in which to write the cloned file.

        Returns:
            Path to the cloned audio file, or ``None`` on failure.
        """
        try:
            self._load_model()

            # Target embedding: cached from color_audio (the voice to clone TO)
            if self._embedding is None:
                self._embedding = self._extract_or_load_embedding(
                    self.config.color_audio_path
                )

            # Source embedding: from the TTS audio (the voice to convert FROM).
            # Cached since all TTS segments share the same TTS engine voice.
            if self._src_embedding is None:
                import openvoice_cli.se_extractor as se_extractor
                self._src_embedding, _ = se_extractor.get_se(
                    tts_audio_path,
                    self._model,
                    vad=True,
                    whisper_device=self._device,
                    compute_type=self._compute_type,
                )

            os.makedirs(output_dir, exist_ok=True)
            filename = f"cloned_{os.path.basename(tts_audio_path)}"
            save_path = os.path.join(output_dir, filename)

            with self._lock:
                self._model.convert(
                    audio_src_path=tts_audio_path,
                    src_se=self._src_embedding,
                    tgt_se=self._embedding,
                    output_path=save_path,
                )
            return save_path
        except Exception as exc:
            self._log_error(f"clone 失败 [{tts_audio_path}]: {exc}")
            return None

    def clone_batch(
        self, items: list[tuple[str, str]]
    ) -> list[Optional[str]]:
        """Concurrently clone multiple TTS audio files.

        Uses ``ThreadPoolExecutor`` with ``self._concurrency`` workers only
        when running in high-VRAM mode (>=4 GB); otherwise falls back to
        sequential processing.

        Args:
            items: List of ``(tts_audio_path, output_dir)`` tuples.

        Returns:
            List of cloned audio paths (``None`` for failed items), in the
            same order as *items*.
        """
        if self._concurrency <= 1:
            return [self.clone(path, out_dir) for path, out_dir in items]

        n = len(items)
        results: list[Optional[str]] = [None] * n

        with ThreadPoolExecutor(max_workers=self._concurrency) as pool:
            futures = {
                pool.submit(self.clone, path, out_dir): idx
                for idx, (path, out_dir) in enumerate(items)
            }
            for future in as_completed(futures):
                idx = futures[future]
                try:
                    results[idx] = future.result()
                except Exception as exc:
                    self._log_error(f"clone_batch worker 异常: {exc}")

        return results

    def device_info(self) -> dict:
        """Return device metadata (matches ``VoiceCloner`` protocol)."""
        return {
            "device": self._device,
            "vram_mb": self._vram_mb,
            "mode": self._mode,
            "concurrency": self._concurrency,
        }

    def cleanup(self) -> None:
        """Release GPU memory and reset internal state."""
        self._model = None
        self._embedding = None
        self._src_embedding = None
        self._unload_whisper()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _resolve_device(raw: str) -> str:
        """Normalise the device string from config."""
        if raw == "auto":
            return "cuda:0" if torch.cuda.is_available() else "cpu"
        return raw

    def _load_model(self) -> None:
        """Lazy-load the ToneColorConverter (GPU or CPU)."""
        if self._model is not None:
            return

        from openvoice_cli.api import ToneColorConverter

        ckpt_dir = os.path.join(
            self.config.model_dir, "openvoice_v2", "converter"
        )
        config_path = os.path.join(ckpt_dir, "config.json")
        ckpt_path = os.path.join(ckpt_dir, "checkpoint.pth")

        self._model = ToneColorConverter(
            config_path,
            device=self._device,
            enable_watermark=self._enable_watermark,
        )
        self._model.load_ckpt(ckpt_path)

    def _cache_path(self, color_audio_path: str) -> str:
        """SHA-256 based path for a persisted embedding tensor."""
        h = hashlib.sha256(color_audio_path.encode()).hexdigest()[:16]
        return os.path.join(self._embedding_cache_dir, f"{h}.pt")

    def _extract_or_load_embedding(
        self, color_audio_path: str
    ) -> torch.Tensor:
        """Return the speaker embedding, using disk cache if available."""
        import openvoice_cli.se_extractor as se_extractor

        self._load_model()

        cache_pth = self._cache_path(color_audio_path)
        if os.path.isfile(cache_pth):
            return torch.load(cache_pth, map_location=self._device)

        embedding, _ = se_extractor.get_se(
            color_audio_path,
            self._model,
            vad=True,
            whisper_device=self._device,
            compute_type=self._compute_type,
        )

        # Persist to disk (saved on CPU to avoid device coupling)
        torch.save(embedding.cpu(), cache_pth)
        embedding = embedding.to(self._device)

        # In CPU mode, aggressively free the Whisper model
        if self._mode == "cpu":
            self._unload_whisper()

        return embedding

    def _unload_whisper(self) -> None:
        """Unload the Whisper model so low-VRAM devices don't OOM."""
        import openvoice_cli.se_extractor as se_extractor

        if se_extractor.model is not None:
            del se_extractor.model
            se_extractor.model = None
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
        gc.collect()

    def _log_error(self, message: str) -> None:
        """Append a timestamped message to the error log."""
        log_path = self.config.error_log_path
        os.makedirs(os.path.dirname(log_path) or ".", exist_ok=True)
        from datetime import datetime

        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(f"[{ts}] {message}\n")
