caption:
  font: ''
  font_size: 0
  font_color: '#ffffff'
  stroke_width: 1.5
  stroke_color: '#f70202'
  bg_color: rgba(0,0,0,128)
  alignment: center
  position: bottom
  max_lines: 2
  max_font_size: 0
  font_size_factor: 0.075
  width_ratio: 0.85
  enable_subtitle_optimization: true
